CREATE TABLE Materials (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE Movements (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  material_id INTEGER,
  type TEXT NOT NULL,
  qty INTEGER NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(material_id) REFERENCES Materials(id)
);
